settings:
  # Время (ч) для удаления королевства после его создания, если кол-во игроков меньше минимума
  disbandDelayHours: 24
  # Время (ч) для удаления королевства после того как игрок покинет королевство, если кол-во игроков меньше минимума
  disbandDelayHoursAfterLeavedPlayer: 72
