modules:
  antiElytra: true
  fastMinecarts: true
  resourcePackSafeLoad: true
  discordsrv: true
  outposts: true
  clanLimiter: true
  kingdomsDiscordsrv: true
kingdomSettings:
  disbandDelayHoursAfterLeavedPlayer: 24
  disbandDelayHours: 12
  disbandPlayerMinimum: 3
  TestConfig: Lorem Ipsum
discord:
  giveDiscordRoleOnKingdomCreation: 1049047181308473395
  defaultKingdomsMessagesChannel: 1247907261616230440
minecartSpeed:
  COPPER_BLOCK: 2.0
  CUT_COPPER: 2.0
  WAXED_COPPER_BLOCK: 1.9
  WAXED_CUT_COPPER: 1.9
  GOLD_BLOCK: 1.75
  EXPOSED_COPPER: 1.75
  EXPOSED_CUT_COPPER: 1.75
  WAXED_EXPOSED_COPPER: 1.65
  WAXED_EXPOSED_CUT_COPPER: 1.65
  WEATHERED_COPPER: 1.5
  WEATHERED_CUT_COPPER: 1.5
  WAXED_WEATHERED_COPPER: 1.4
  WAXED_WEATHERED_CUT_COPPER: 1.4
  OXIDIZED_COPPER: 1.25
  OXIDIZED_CUT_COPPER: 1.25
  WAXED_OXIDIZED_COPPER: 1.15
  WAXED_OXIDIZED_CUT_COPPER: 1.15
  DIRT: 0.35
  GRAVEL: 0.3
  SOUL_SAND: 0.2
storage: