kingdomSettings:
  disbandDelayHoursAfterLeavedPlayer: 24
  disbandDelayHours: 12
  disbandPlayerMinimum: 3
  TestConfig: Lorem Ipsum
  giveDiscordRoleOnKingdomCreation: 1049047181308473395
  defaultKingdomsMessagesChannel: 1247907261616230440
storage: