name: AntagonCore
version: '${project.version}'
main: com.aquobus.antagoncore.AntagonCore
api-version: '1.21'
description: Main plugin for Antagon server
softdepend:
  - Kingdoms
  - DiscordSRV
  - LuckPerms
commands:
  antagoncore:
    description: Главная команда для плагина AntagonCore
    usage: /<command> <argument>
    aliases:
      - anc
      - ac
      - acore
    permission: antagoncore.admin
    permission-message: У вас нет разрешения на использование этой команды!
permissions:
  antagoncore.admin:
    description: Allows to use antagoncore commands
    default: op