name: AntagonCore
version: '${project.version}'
main: com.aquobus.antagoncore.AntagonCore
api-version: '1.20.4'
description: Main plugin for Antagon server
softdepend:
  - Kingdoms
  - DiscordSRV
commands:
  antagoncore:
    description: Главная команда для плагина AntagonCore
    usage: /<command> <argument>
    aliases:
      - anc
      - ac
      - acore